apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: dGVzdHBhc3N3b3Jk
  DB_NAME: d2ViYXBw
  DB_HOST: cG9zdGdyZXMtMC5wb3N0Z3Jlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs